### PR TITLE
Disable coverage/pytest warnings

### PR DESCRIPTION
**Pull request by epelaaez**
fixes https://github.com/Infleqtion/server-superstaq/issues/2406

### CODE REVIEW

**Review by vtomole — CHANGES_REQUESTED** [review]
We want to disable specific warnings. Can we only disable the warnings coming from `qiskit`? That's what's flooding our terminal. Even better: is it easy to fix those qiskit warnings?

**Comment by epelaaez** [comment]
> Can we only disable the warnings coming from qiskit? 

I think we can do something like: https://stackoverflow.com/a/53218641/13579299.

**Comment by richrines1** [comment]
> We want to disable specific warnings. Can we only disable the warnings coming from `qiskit`?

we already do this for some qtrl warnings server-side: https://github.com/Infleqtion/server-superstaq/blob/main/pytest.ini

**Comment by richrines1** [comment]
> Even better: is it easy to fix those qiskit warnings?

looked into this briefly, basically all the warnings appear as soon as `qiskit_ibm_runtime` is imported in a pytest - they still appear even if you just save a file like
```python
### foo.py

import qiskit_ibm_runtime

def test_foo():
    pass
```
and run
```
pytest foo.py
```
so afaik the only way to avoid suppressing the warnings is to file an issue on qiskit_ibm_runtime

**Comment by epelaaez** [comment]
> we already do this for some qtrl warnings server-side

so this can be done server-side without changing anything here?

**Comment by epelaaez** [comment]
closed as superseded by https://github.com/Infleqtion/server-superstaq/pull/2491

**Pull request closed without merging**
