### PR TITLE
lazy-load qss backend configuration

### LINKED ISSUE #772: `provider.backends()` is too slow
### What is happening?

running `provider.backends()` is taking 45-60s to complete. About 15s of this is the time it takes to get the list of targets (and so this is about how long `css.Service().get_targets()` takes), The remaining 30s is just due to the calls to `target_info` for each backend

imo we should be returning more info from the get_targets endpoint to obviate the need for all the subsequent target_info calls, and anything not returned as part of `get_targets` should be lazily retrieved by backends if necessary

### How can we reproduce the issue?

```python
provider = qss.SuperstaqProvider()
service = css.Service()

t0 = time.time()
_ = provider.backends()
t1 = time.time()
_ = service.get_targets()
t2 = time.time()

print("provider.get_backends():", t1 - t0)
print("service.get_targets():", t2 - t1)
```
which just gave me
```
provider.get_backends(): 44.30445456504822
service.get_targets(): 14.650813341140747
```

### What should happen?

provider.backends() shouldn't take much longer than service.get_targets(), or about 15s (ideally both should be faster)

### Environment

- **Superstaq version**: 0.4.37
- **client-superstaq version**: 0.4.22

### Any additional context?

_No response_

### PR DESCRIPTION
**Pull request by richrines1**
fixes #772

### CODE REVIEW

**Review by bharat-thotakura — APPROVED** [review]
LGTM

(Testing locally, `get_backends()` and `get_targets()` are now comparable in terms of time taken!)

**Comment by bharat-thotakura** [comment]
Should we revert https://github.com/Infleqtion/client-superstaq/pull/892/commits/1f953b0ca01fc19b907e4a889d846beaf9333e0e after merging this PR?

**Comment by richrines1** [comment]
> Should we revert [1f953b0](https://github.com/Infleqtion/client-superstaq/commit/1f953b0ca01fc19b907e4a889d846beaf9333e0e) after merging this PR?

ah good question. i think the first change in that commit should be reverted (and is small enough that i'll just add it to this pr). i kinda feel like the others are maybe nicer as they are though? imo the `get_targets` output is more interesting/informative than showing the output of `backends()` now.. wdyt?

**Comment by bharat-thotakura** [comment]
Yeah sure, I'd agree with that and I guess it keeps both the `css` and `qss` notebook outputs w.r.t. targets the same

**Pull request merged**
