### PR TITLE
adding back in module info for clients

### PR DESCRIPTION
**Pull request by stephanielee9**
Adding API module info back into docs (noting that this brings up the old warnings when you build docs)

### CODE REVIEW

**Comment by cdbf1** [comment]
I think this has actually be separately completed by https://github.com/Infleqtion/client-superstaq/pull/1030

**Comment by vtomole** [comment]
image

**Comment by stephanielee9** [comment]
Not a huge issue but I had left this open before because I hadn't yet figured out why these semicolons were in the docs - do we care about them?
image

**Comment by cdbf1** [comment]
> Not a huge issue but I had left this open before because I hadn't yet figured out why these semicolons (between Parameters and Returns here) were in the docs - do we care about them? image

Ah yeah, these colons have been bugging me for ages and I can't work it out! I'm wondering if there is something in our css that is causing a bug somewhere

**Comment by cdbf1** [comment]
Update: I have located the source of the random colons in the html. Sphinx is currently generating html like:
```
<dt class="field-even">Returns<span class="colon">:</span></dt>
```

However, removing the `<span>` tag: 
```
<dt class="field-even">Returns</dt>
```
Removes the spurious comma, while *keeping* the single comma after `Return`.

Next step is to work out how we can stop sphinx adding the `<span>` tags.

**Pull request closed without merging**
