### PR TITLE
Version bump to 0.5.22

### PR DESCRIPTION
**Pull request by spencerdearman**
Version bump to 0.5.21 -> 0.5.22

### CODE REVIEW

**Comment by bharat-thotakura** [comment]
I think we may be able to merge https://github.com/Infleqtion/client-superstaq/pull/998 and #1008 before deploying

**Comment by spencerdearman** [comment]
Ah ok @bharat-thotakura, I will move this to a draft.

**Comment by richrines1** [comment]
let's merge #1007 before deploying too

**Comment by bharat-thotakura** [comment]
I think we have already have a fair amount of new updates after merging https://github.com/Infleqtion/client-superstaq/pull/1010 to deploy client

**Comment by spencerdearman** [comment]
will deploy now @bharat-thotakura

**Review by bharat-thotakura — APPROVED** [review]
LGTM

**Pull request merged**
