### PR TITLE
Fix passing of dd_strategy kwargs in compile

### PR DESCRIPTION
**Pull request by paaige**

### CODE REVIEW

**Comment by richrines1** [comment]
needs superstaq_provider too i think

**Comment by richrines1** [comment]
can we also add something like this: https://github.com/Infleqtion/client-superstaq/blob/900f50948c87090e34f08029f2751a56f8db17f6/qiskit-superstaq/qiskit_superstaq/superstaq_provider_test.py#L250-L254
(but with `dd_strategy`/etc) to `test_ibmq_compile` as a regression test?

**Comment by paaige** [comment]
> can we also add something like this:
> 
> https://github.com/Infleqtion/client-superstaq/blob/900f50948c87090e34f08029f2751a56f8db17f6/qiskit-superstaq/qiskit_superstaq/superstaq_provider_test.py#L250-L254
> 
> 
> (but with `dd_strategy`/etc) to `test_ibmq_compile` as a regression test?

Added tests to all (css:service, qss:provider/backend)

**Comment by richrines1** [comment]
> Added tests to all (css:service, qss:provider/backend)

thanks! does the service_test update still need to be pushed by any chance? looks like the file is unchanged

**Comment by paaige** [comment]
> > Added tests to all (css:service, qss:provider/backend)
> 
> thanks! does the service_test update still need to be pushed by any chance? looks like the file is unchanged

... yeah, good catch! thanks

**Review by richrines1 — APPROVED** [review]
lgtm % formatting! thanks for catching this

**Pull request merged**
