### PR TITLE
version bump to `0.4.0`

### PR DESCRIPTION
**Pull request by dowusu-antwi**
Will merge after https://github.com/Infleqtion/client-superstaq/pull/562, https://github.com/Infleqtion/client-superstaq/pull/571/, #573 are merged.

### CODE REVIEW

**Comment by richrines1** [comment]
probably time for `0.4.0` instead of `0.3.34` (but if so we should probably merge #573 first too)

**Review by bharat-thotakura — APPROVED** [review]
LGTM (though if possible wait for #574 to also be merged haha)

**Comment by dowusu-antwi** [comment]
> LGTM (though if possible wait for #574 to also be merged haha)

No problem lol. Will wait for https://github.com/Infleqtion/client-superstaq/pull/574 and #573.

**Comment by richrines1** [comment]
> No problem lol. Will wait for #574 and #573.

sorry #575 too lol

**Review by vtomole — COMMENTED** [review]
Let's wait on merging until https://github.com/Infleqtion/client-superstaq/issues/569 is done. Shouldn't take long

**Comment by vtomole** [comment]
Done https://github.com/Infleqtion/client-superstaq/pull/576

**Pull request merged**
