### PR TITLE
Update readme animation

### PR DESCRIPTION
**Pull request by stephanielee9**
Closes https://github.com/Infleqtion/client-superstaq/issues/649

### CODE REVIEW

**Review by vtomole — APPROVED** [review]

**Comment by richrines1** [comment]
out of curiosity is there a reason we don't show the output of the last line?

**Comment by vtomole** [comment]
>  i guess it would be a bit misleading because it would show the results coming back nearly instantly..

This is fine cause the passed in backend is a simulator. I always thought we don't do that cause we don't want to have too much info in the gif.

**Comment by stephanielee9** [comment]
@vtomole @richrines1 just let me know if you prefer it - i can add it as a comment in the bottom line

**Comment by vtomole** [comment]
This is a huge nit to me so I'm fine with what we have.

**Comment by richrines1** [comment]
> I always thought we don't do that cause we don't want to have too much info in the gif.

i don't think it's too much to show something like `{"00": 47, "11": 53}`, and imo it seems a little incomplete without it (tbh i thought my browser was hesitating or something when i first watched it)

(not necessarily related to this pr though)

**Comment by stephanielee9** [comment]
@vtomole @richrines1 added the counts as a last line in the comments

**Review by vtomole — APPROVED** [review]
Noice  :+1:

**Review by richrines1 — APPROVED** [review]
awesome :) thanks!

**Comment by stephanielee9** [comment]
Yeah of course! Also not sure where this comment should really go but the files changed makes it look like I'm making a new image (e.g., like I'm making something in Photoshop and dropping in into the folder), but I'm just updating a few lines of code in the svg file in case people want to make updates in the future

**Pull request merged**
