### PR TITLE
rewrite `qss.serialize_circuits` to support newest qiskit

### PR DESCRIPTION
**Pull request by richrines1**
also adds workarounds for a number of known qpy bugs, and fixes some bugs in our previous implementation (which didn't recurse into gate .definitions, and therefore could break or silently modify gates if circuits weren't flattened prior to submission)

fixes: #837

(notebook checks won't pass until after this is deployed)

### CODE REVIEW

**Comment by vtomole** [comment]
@SalahedeenIssa please review

**Comment by SalahedeenIssa** [comment]
@vtomole was waiting for checks to pass - I'll review it later today

**Comment by richrines1** [comment]
> was waiting for checks to pass

we'll have to bypass the notebook check - it won't pass until after this has been deployed

**Review by SalahedeenIssa — APPROVED** [review]
lgtm!

**Comment by SalahedeenIssa** [comment]
can it be merged/deployed without passing all tests?

**Comment by richrines1** [comment]
> can it be merged/deployed without passing all tests?

yep, temporarily disabled the requirement :)

**Pull request merged**
