### PR TITLE
bump version to 0.5.25

### PR DESCRIPTION
**Pull request by richrines1**

### CODE REVIEW

**Review by vtomole — APPROVED** [review]
LGTM

**Comment by bharat-thotakura** [comment]
(seems like we can merge https://github.com/Infleqtion/client-superstaq/pull/1003 also -- if not already waiting)

**Review by bharat-thotakura — APPROVED** [review]
LGTM with https://github.com/Infleqtion/client-superstaq/pull/1037 as well

**Comment by pgoiporia** [comment]
Is this good to go in?

**Comment by richrines1** [comment]
> Is this good to go in?

yep sorry had been trying to get a few other tweaks in quickly before publishing, but this is ready to go as soon as the tests pass

**Pull request merged**
