### PR TITLE
Update to Superstaq naming in docs + css + qss

### PR DESCRIPTION
**Pull request by bharat-thotakura**
Updates naming from SuperstaQ to Superstaq as part of https://github.com/Infleqtion/client-superstaq/issues/531

### CODE REVIEW

**Comment by richrines1** [comment]
fwiw running this from the repo root should change every instance in the repo:
```bash
sed -e 's/SuperstaQ/Superstaq/g' -i $(git ls-files $(find -type f))
```

**Comment by bharat-thotakura** [comment]
> fwiw running this from the repo root should change every instance in the repo:
> 
> ```shell
> sed -e 's/SuperstaQ/Superstaq/g' -i $(git ls-files $(find -type f))
> ```

Yeah, I tried that at first but it changed SuperstaQClient -> SuperstaqClient (etc.) which caused some errors. So I reverted and did manual edits where applicable. Left some notebooks since they will be replaced with the updated tutorials

**Comment by richrines1** [comment]
> changed SuperstaQClient -> SuperstaqClient (etc.)

isn't this what we want?

**Comment by bharat-thotakura** [comment]
> > changed SuperstaQClient -> SuperstaqClient (etc.)
> 
> isn't this what we want?

Oh, that issue is part of #2375 and this PR was meant just for #531 (docs update). Though maybe it's better just to make it one combined PR.

**Comment by richrines1** [comment]
> Oh, that issue is part of the server-side [Infleqtion/server-superstaq#2375](https://github.com/Infleqtion/server-superstaq/issues/2375) and this PR was meant just for #531 (docs update)

ahh my bad, i was just looking at the pr title

> Though maybe it's better just to make it one combined PR.

either way - whichever you think is easiest! changing the class names will also require a corresponding server-side update (which shouldn't be too bad either i think)

**Review by knsmith — APPROVED** [review]
Checked the changed files and everything looks good to me! Like separating docs changes from code to keep the PRs more manageable.

**Pull request merged**
