### PR TITLE
Update Superstaq DD notebook

### PR DESCRIPTION
**Pull request by knsmith**
Include SS compile in the flow.

### CODE REVIEW

**Review by paaige — APPROVED** [review]
Looks good, just need to run .check/format_.py --apply

**Comment by knsmith** [comment]
> View / edit / reply to [this conversation](https://app.reviewnb.com/Infleqtion/client-superstaq/pull/763/discussion/#comment-1717931865) on ReviewNB
> 
> _richrines1 commented on 2023-09-13T16:13:33Z_ ----------------------------------------------------------------
> 
> Line #15.        for i in range(circuit_width - 1):
> 
> might be good to add another barrier before the measurements - it won't change our compiled circuit at all (we're right-aligning anyway) but will make the circuit diagram a bit cleaner

decided against this for now

**Comment by knsmith** [comment]
> View / edit / reply to [this conversation](https://app.reviewnb.com/Infleqtion/client-superstaq/pull/763/discussion/#comment-1717931900) on ReviewNB
> 
> _richrines1 commented on 2023-09-13T16:13:35Z_ ----------------------------------------------------------------
> 
> Line #1.    qc_4_optimized = qiskit.transpile(qc_4, ibm_backend, optimization_level=3)
> 
> i think we should use more clear variable names for the circuits, e.g. something like input_circuit/qiskit_optimized_circuit/superstaq_optimized_circuit

done!

**Comment by knsmith** [comment]
> View / edit / reply to [this conversation](https://app.reviewnb.com/Infleqtion/client-superstaq/pull/763/discussion/#comment-1718315595) on ReviewNB
> 
> _richrines1 commented on 2023-09-13T21:04:30Z_ ----------------------------------------------------------------
> 
> Line #4.    provider = qss.SuperstaqProvider(api_key='3196d09600e23e4c57b1cc9f149e77c7bf5774c5ec28bd06c4f641c9a990ac41')
> 
> oops - need to refresh this key now

yes! already on it! pushed the wrong notebook....

**Comment by knsmith** [comment]
> View / edit / reply to [this conversation](https://app.reviewnb.com/Infleqtion/client-superstaq/pull/763/discussion/#comment-1718315581) on ReviewNB
> 
> _richrines1 commented on 2023-09-13T21:04:29Z_ ----------------------------------------------------------------
> 
> Line #8.        print("Installed qiskit-superstaq. Please restart the kernel to import the packages.")
> 
> it looks like this is reverting the language updates made in #760?

good point. I think i started working on this before #760 was merged....adjusting

**Comment by knsmith** [comment]
fixed the cell numbering

**Comment by paaige** [comment]
Okay I sort of prematurely approved this but once rich's comments are addressed I'll let him do final approval and I'll reincorporate the strategies from [this older commit](https://github.com/Infleqtion/client-superstaq/issues/761)

**Review by richrines1 — APPROVED** [review]
lgtm!

**Pull request merged**
