### PR TITLE
Update `pip install` command in notebooks

### LINKED ISSUE #612: Update tutorial install instructions
Update install instructions to:
```
try:
  import qiskit
  import qiskit_superstaq as qss
except ImportError:
  print("Installing qiskit-superstaq...")
  %pip install -q qiskit-superstaq[examples]
  print("Installed qiskit-superstaq")
```

### PR DESCRIPTION
**Pull request by bharat-thotakura**
Fixes #612

### CODE REVIEW

**Review by epelaaez — APPROVED** [review]
lgtm!

**Comment by bharat-thotakura** [comment]
Thanks, @epelaaez! @vtomole, is there anything else that should be added?

**Comment by vtomole** [comment]
> is there anything else that should be added?

Noope

**Review by vtomole — APPROVED** [review]
LGTM

**Pull request merged**
