### PR TITLE
aqt notebook updates

### PR DESCRIPTION
**Pull request by richrines1**
qss notebook won't run until server-side changes are deployed

doesn't include qutrit compilation (will add in a separate pr)

### CODE REVIEW

**Comment by stephanielee9** [comment]
@richrines1 could you update the `aqt.rst` file so it has a little description (can be just a couple sentences) - references not necessary unless you have a good article to add. Example [here](https://superstaq.readthedocs.io/en/latest/optimizations/ibm/ibm.html).

**Comment by richrines1** [comment]
> @richrines1 could you update the `aqt.rst` file so it has a little description (can be just a couple sentences) - references not necessary unless you have a good article to add. Example [here](https://superstaq.readthedocs.io/en/latest/optimizations/ibm/ibm.html).

done.

**Review by stephanielee9 — CHANGES_REQUESTED** [review]
Just some nits but otherwise looks good! I'll leave the final approve to @epelaaez since he reviewed the notebooks initially

**Comment by richrines1** [comment]
thanks! (@stephanielee9 think you still have to approve because you had requested changes)

**Pull request merged**
