### PR TITLE
version bump to v0.4.27

### PR DESCRIPTION
**Pull request by stephanielee9**

### CODE REVIEW

**Comment by bharat-thotakura** [comment]
Would it be possible to wait for https://github.com/Infleqtion/client-superstaq/pull/816?

**Comment by stephanielee9** [comment]
@bharat-thotakura yeah for sure - just ping me when it's in

**Comment by bharat-thotakura** [comment]
> @bharat-thotakura yeah for sure - just ping me when it's in

Thanks! It's under review now. Also, I approved https://github.com/Infleqtion/client-superstaq/pull/728 to be merged --unless you want to make further changes @stephanielee9

**Comment by stephanielee9** [comment]
> > @bharat-thotakura yeah for sure - just ping me when it's in
> 
> Thanks! It's under review now. Also, I approved #728 to be merged --unless you want to make further changes @stephanielee9

I had been thinking about waiting until the $ --> credits PR was merged but I see it's in so I'll do one last look through and merge that PR in!

**Comment by bharat-thotakura** [comment]
> Would it be possible to wait for #816?

@stephanielee9 #816 has been merged

**Pull request merged**
